55 update sample app to showcase the usage
endatix/endatix pull request #94
Opened 2024-09-10 15:50 UTC by orilux

# Sample app with NuGet ackages

## Description
Added a sample app that follows the official installation guide. Added readme files to alll sampl app folders.

## Related Issues
none

## Type of Change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots
If applicable, add screenshots to help explain your changes.

2024-09-12 18:04 UTC, dspetrov approved these changes
I approve but have one comment. @orilux, please have a look at it.

2024-09-12 18:04 UTC, dspetrov commented on samples/Endatix.Samples.SelfHosted/Endatix.Samples.SelfHosted.sln
Is it intentionally that there is a solution file for this sample app?
Generally it is a project added to the Endatix.sln file and also the other sample apps do not have own solution files. If there is a need, them we should consider adding .sln files to all sample apps.

2024-09-12 21:17 UTC, orilux commented on samples/Endatix.Samples.SelfHosted/Endatix.Samples.SelfHosted.sln
@dspetrov thanks for catching this. It is an error on my part - I did add the new project to the main solution after I realized it, but I forgot to delete the old solution file.

2024-09-13 04:17 UTC, PeterMarinov commented on samples/Endatix.Samples.SelfHosted/Endatix.Samples.SelfHosted.sln
To add to that, I think that each sample should be atomic and independent from the rest and because of that we don't need Samples solution file as well. We can add dependabot at some point and automatically update the NuGets and other dependencies of our samples and run tests to maintain them easier if they are separate projects - one per root folder.

Learn more at (https://github.com/dependabot)

2024-09-17 14:14 UTC, orilux reviewed
Removed the unnecessary SLN file as the project has been added to the main one.

2024-09-17 14:14 UTC, orilux commented on samples/Endatix.Samples.SelfHosted/Endatix.Samples.SelfHosted.sln
Removed the unnecessary SLN file. Thanks!

2024-09-17 14:39 UTC, PeterMarinov requested changes

2024-09-17 14:39 UTC, PeterMarinov commented on Endatix.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Endatix.Samples.SelfHosted", "samples\Endatix.Samples.SelfHosted\Endatix.Samples.SelfHosted.csproj", "{7C38EFD4-B5DB-4128-A180-849E54EB80F2}"
@orilux  - you need to remove this reference too.

2024-09-17 14:52 UTC, PeterMarinov commented on Endatix.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Endatix.Samples.SelfHosted", "samples\Endatix.Samples.SelfHosted\Endatix.Samples.SelfHosted.csproj", "{7C38EFD4-B5DB-4128-A180-849E54EB80F2}"
Please ignore. Let's leave it as it is and all samples will remain referenced in the main solution for ease of use for fellow developers. This is how MediatR have also structured their repo

2024-09-17 14:53 UTC, PeterMarinov approved these changes
Approving

2024-09-17 14:53 UTC, merged